steps:

  # Step 3: Create VM if not exists
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Create BaGet VM'
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        VM_EXISTS=$$(gcloud compute instances list --filter="name=baget-vm" --zones=asia-south1-c --format="value(name)")
        if [ -z "$$VM_EXISTS" ]; then
          echo "Creating VM..."
          gcloud compute instances create baget-vm \
            --zone=asia-south1-c \
            --machine-type=e2-medium \
            --image-family=debian-11 \
            --image-project=debian-cloud \
            --tags=http-server \
            --metadata=startup-script='#!/bin/bash
              sudo apt update
              sudo apt install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker'
        else
          echo "VM already exists, skipping."
        fi

  # Step 4: Copy Dockerfile and BaGet key to VM
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Copy Dockerfile and Key'
    entrypoint: bash
    args:
      - -c
      - |
        mkdir temp-baget
        cp Dockerfile temp-baget/
        echo "$$GCP_SA_KEY_JSON" > temp-baget/baget-key.json
        gcloud compute scp --recurse temp-baget baget-vm:~/baget --zone=asia-south1-c

  # Step 5: SSH into VM, build BaGet Docker image and run container
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Run BaGet in VM'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud compute ssh baget-vm --zone=asia-south1-c --command='
          cd ~/baget
          sudo docker build -t baget-server .
          sudo docker stop baget || true
          sudo docker rm baget || true
          sudo docker run -d --name baget -p 8080:8080 \
            -e ASPNETCORE_ENVIRONMENT=Production \
            -e BAGET__Storage__Type=GoogleCloudStorage \
            -e BAGET__Storage__GoogleCloudStorage__Bucket=my-dotnet-packages1 \
            -e BAGET_API_KEY=my-secret-api-key \
            -e GOOGLE_APPLICATION_CREDENTIALS=/app/baget-key.json \
            -v /home/$(whoami)/baget/baget-key.json:/app/baget-key.json \
            baget-server
        '

availableSecrets:
  secretManager:
    - versionName: projects/onyx-antler-459216-j6/secrets/GCP_SA_KEY/versions/latest
      env: GCP_SA_KEY_JSON

options:
  logging: CLOUD_LOGGING_ONLY
